#!/usr/bin/env python3
"""Executable entry point: ./bcurl -v host:port/path"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from binhttp.client import main

if __name__ == "__main__":
    sys.exit(main())
